[[redirects]]
	from="/*"
	to="index.html"
	status=200

[build]
  	# base = ""
  	command = "npm run build"
  	publish = "dist"
	# functions = "functions/"

[[headers]]
	for = "static/*"
	[headers.values]
		cache-control = '''
		public,
		max-age=31536000'''